language: android
script: "./gradlew build"
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  skip_cleanup: true
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-19
    - extra-android-m2repository
